version: "3.0"
services:
  elastic:
    container_name: es-app
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    # build: .
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
    volumes:
      - "./elastic/data:/usr/share/elasticsearch/data"
      - "./elastic/logs:/usr/share/elasticsearch/logs"
    restart: always
    networks:
      - esnet
    ports:
      - 9200:9200
  kibana:
    container_name: kibana-app
    image: docker.elastic.co/kibana/kibana:8.6.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://es-app:9200
    networks:
      - esnet
    depends_on:
      - elastic
    ports:
      - 5601:5601
networks:
  esnet:
    driver: bridge



